/* ============================================================
   Studio 27 — gedeelde dataset (CRM = source of truth)
   Wordt geladen in zowel CRM.dc.html als Finance.dc.html.
   Eén bron voor offertes, bedrijven en contacten.
   ============================================================ */
(function(){
  if (typeof window === 'undefined') return;
  if (window.S27_DATA) return; // al geladen

  var companies = [
    { id:'bolckmans', name:'Bolckmans NV', kaart:'klant', org:'S27', sS27:'Actief klant', s27A:'In progress', sZVD:'Geen potentieel', pm:'Ilke', website:'bolckmans.be', locatie:'Hoogstraten', kbo:'BE 0765.378.104', mw:120, factEmail:'facturatie@bolckmans.be', factOpm:'PO-nummer verplicht op factuur.', drive:'drive.google.com/bolckmans', typeJob:'Webdesign', hoofd:'c1', ga4:'G-8KD2BX4', gsc:'https://bolckmans.be/', gads:'419-882-7741', meta:'ACT-99812', metaBiz:'BM-44120', tiktok:'—', snap:'—', metricool:'MC-7781', webflow:'WF-bolck-22', editor:'webflow.com/bolckmans', portaalUrl:'portaal.studio27.be/bolckmans', portaalToken:'bk_9f33ad21', portaalToegang:'Actief', modules:['Performance','Socials-bewerkbaar'], ads:true, sector:'Industrie- en betonbouw' },
    { id:'flor', name:'Flor Vastgoed', kaart:'klant', org:'27A', sS27:'Geen potentieel', s27A:'Actief klant', sZVD:'Geen potentieel', pm:'Ilke', website:'florvastgoed.be', locatie:'Turnhout', kbo:'BE 0712.554.901', mw:14, factEmail:'admin@florvastgoed.be', factOpm:'Maandelijkse retainer.', drive:'drive.google.com/flor', typeJob:'Automations', hoofd:'c4', ga4:'G-FLOR221', gsc:'https://florvastgoed.be/', gads:'—', meta:'ACT-55120', metaBiz:'BM-22110', tiktok:'—', snap:'—', metricool:'MC-3320', webflow:'—', editor:'—', portaalUrl:'portaal.studio27.be/flor', portaalToken:'fl_22b8cc04', portaalToegang:'Actief', modules:['Performance'], ads:true, sector:'Vastgoed' },
    { id:'raes', name:'Dr. Melanie Raes', kaart:'potentiele klant', org:'S27', sS27:'Potentieel', s27A:'Geen potentieel', sZVD:'Potentieel', pm:'Arne', website:'dermaraes.be', locatie:'Brasschaat', kbo:'BE 0698.221.330', mw:6, factEmail:'praktijk@dermaraes.be', factOpm:'', drive:'—', typeJob:'Branding', hoofd:'c6', ga4:'—', gsc:'—', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'—', webflow:'—', editor:'—', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:false, sector:'Medisch' },
    { id:'partspoint', name:'PartsPoint België', kaart:'potentiele klant', org:'S27', sS27:'In progress', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Ilke', website:'partspoint.be', locatie:'Antwerpen', kbo:'BE 0644.119.872', mw:240, factEmail:'finance@partspoint.be', factOpm:'', drive:'drive.google.com/partspoint', typeJob:'Video- en fotografie', hoofd:'c7', ga4:'G-PP4421', gsc:'https://partspoint.be/', gads:'771-220-9981', meta:'ACT-77321', metaBiz:'BM-91002', tiktok:'TT-44120', snap:'—', metricool:'—', webflow:'—', editor:'—', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:true, sector:'Automotive' },
    { id:'abw', name:'ABW Bestratingen', kaart:'klant', org:'S27', sS27:'Actief klant', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Ilke', website:'abwbestratingen.be', locatie:'Merksplas', kbo:'BE 0688.443.120', mw:32, factEmail:'info@abwbestratingen.be', factOpm:'', drive:'drive.google.com/abw', typeJob:'SEO', hoofd:'c9', ga4:'G-ABW991', gsc:'https://abwbestratingen.be/', gads:'330-118-7741', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'MC-1190', webflow:'WF-abw-09', editor:'webflow.com/abw', portaalUrl:'portaal.studio27.be/abw', portaalToken:'ab_71cc20', portaalToegang:'Actief', modules:['Performance'], ads:false, sector:'Bestrating' },
    { id:'vorsselmans', name:'Vorsselmans Solar', kaart:'klant', org:'S27', sS27:'Actief klant', s27A:'Potentieel', sZVD:'Geen potentieel', pm:'Johanna', website:'vorsselmans.be', locatie:'Brecht', kbo:'BE 0677.991.200', mw:55, factEmail:'boekhouding@vorsselmans.be', factOpm:'', drive:'drive.google.com/vorsselmans', typeJob:'Adverteren', hoofd:'c10', ga4:'G-VS7720', gsc:'https://vorsselmans.be/', gads:'882-447-1190', meta:'ACT-33129', metaBiz:'BM-77810', tiktok:'—', snap:'—', metricool:'MC-9981', webflow:'—', editor:'—', portaalUrl:'portaal.studio27.be/vorsselmans', portaalToken:'vs_4490ab', portaalToegang:'Actief', modules:['Performance','Socials-bewerkbaar'], ads:true, sector:'Zonne-energie' },
    { id:'gtfoam', name:'GT Foam', kaart:'potentiele klant', org:'S27', sS27:'Potentieel', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Arne', website:'gtfoam.com', locatie:'Geel', kbo:'BE 0701.882.443', mw:48, factEmail:'sales@gtfoam.com', factOpm:'', drive:'—', typeJob:'Social media', hoofd:'c12', ga4:'—', gsc:'—', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'—', webflow:'—', editor:'—', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:false, sector:'Productie' },
    { id:'orison', name:'Orison', kaart:'klant', org:'S27', sS27:'Actief klant', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Johanna', website:'orison.be', locatie:'Mol', kbo:'BE 0655.330.118', mw:21, factEmail:'hello@orison.be', factOpm:'', drive:'drive.google.com/orison', typeJob:'Adverteren', hoofd:'c13', ga4:'G-OR5510', gsc:'https://orison.be/', gads:'118-993-2210', meta:'ACT-66120', metaBiz:'BM-33201', tiktok:'—', snap:'SC-2210', metricool:'MC-6610', webflow:'—', editor:'—', portaalUrl:'portaal.studio27.be/orison', portaalToken:'or_99c1bb', portaalToegang:'Actief', modules:['Performance'], ads:true, sector:'Retail' },
    { id:'maxpro', name:'Max Pro', kaart:'klant', org:'S27', sS27:'Geen actieve klant meer', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Arne', website:'maxpro.be', locatie:'Herentals', kbo:'BE 0633.220.991', mw:9, factEmail:'info@maxpro.be', factOpm:'Traject gepauzeerd.', drive:'—', typeJob:'Webdesign', hoofd:'c14', ga4:'—', gsc:'—', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'—', webflow:'—', editor:'—', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:false, sector:'Groothandel' },
    { id:'ipcleaning', name:'IP Cleaning', kaart:'klant', org:'S27', sS27:'Geen actieve klant meer', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Ilke', website:'ipcleaning.be', locatie:'Hoogstraten', kbo:'BE 0699.118.220', mw:67, factEmail:'admin@ipcleaning.be', factOpm:'', drive:'drive.google.com/ipcleaning', typeJob:'SEO', hoofd:'c15', ga4:'G-IP2210', gsc:'https://ipcleaning.be/', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'—', webflow:'WF-ip-04', editor:'webflow.com/ip', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:false, sector:'Schoonmaak' },
    { id:'rodenburgh', name:'Rodenburgh', kaart:'klant', org:'S27', sS27:'Actief klant', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Ilke', website:'rodenburgh.be', locatie:'Schilde', kbo:'BE 0712.554.118', mw:18, factEmail:'office@rodenburgh.be', factOpm:'', drive:'drive.google.com/rodenburgh', typeJob:'Branding', hoofd:'c16', ga4:'G-RB1120', gsc:'https://rodenburgh.be/', gads:'—', meta:'ACT-11220', metaBiz:'BM-55012', tiktok:'—', snap:'—', metricool:'MC-2231', webflow:'—', editor:'—', portaalUrl:'portaal.studio27.be/rodenburgh', portaalToken:'rb_33aa90', portaalToegang:'Actief', modules:['Socials-bewerkbaar'], ads:true, sector:'Horeca' },
    { id:'genechten', name:'Maarten Van Genechten', kaart:'potentiele klant', org:'S27', sS27:'Potentieel', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Arne', website:'mvg-coaching.be', locatie:'Westerlo', kbo:'BE 0744.221.667', mw:1, factEmail:'maarten@mvg-coaching.be', factOpm:'', drive:'—', typeJob:'Strategie', hoofd:'c17', ga4:'—', gsc:'—', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'—', webflow:'—', editor:'—', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:false, sector:'Coaching' },
    { id:'gyma', name:'Gyma', kaart:'klant', org:'S27', sS27:'Actief klant', s27A:'Geen potentieel', sZVD:'Geen potentieel', pm:'Ilke', website:'gyma.be', locatie:'Lille', kbo:'BE 0688.110.554', mw:38, factEmail:'finance@gyma.be', factOpm:'', drive:'drive.google.com/gyma', typeJob:'Social media', hoofd:'c18', ga4:'G-GY7710', gsc:'https://gyma.be/', gads:'—', meta:'ACT-88120', metaBiz:'BM-22091', tiktok:'TT-99120', snap:'—', metricool:'MC-5510', webflow:'—', editor:'—', portaalUrl:'portaal.studio27.be/gyma', portaalToken:'gy_77bc11', portaalToegang:'Actief', modules:['Socials-bewerkbaar'], ads:true, sector:'Voeding' },
    { id:'farmamatch', name:'Farmamatch', kaart:'potentiele klant', org:'ZVD', sS27:'Geen potentieel', s27A:'Geen potentieel', sZVD:'In progress', pm:'Arne', website:'farmamatch.be', locatie:'Leuven', kbo:'BE 0755.220.118', mw:12, factEmail:'info@farmamatch.be', factOpm:'', drive:'—', typeJob:'Strategie', hoofd:'c19', ga4:'—', gsc:'—', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'—', webflow:'—', editor:'—', portaalUrl:'—', portaalToken:'—', portaalToegang:'Geen', modules:[], ads:false, sector:'Zorg' },
    { id:'eyematch', name:'Eyematch', kaart:'klant', org:'ZVD', sS27:'Geen potentieel', s27A:'Geen potentieel', sZVD:'Actief klant', pm:'Ilke', website:'eyematch.be', locatie:'Gent', kbo:'BE 0701.554.229', mw:24, factEmail:'admin@eyematch.be', factOpm:'', drive:'drive.google.com/eyematch', typeJob:'Webdesign', hoofd:'c20', ga4:'G-EM2290', gsc:'https://eyematch.be/', gads:'—', meta:'—', metaBiz:'—', tiktok:'—', snap:'—', metricool:'MC-8810', webflow:'WF-em-11', editor:'webflow.com/eyematch', portaalUrl:'portaal.studio27.be/eyematch', portaalToken:'em_22dd09', portaalToegang:'Actief', modules:['Performance'], ads:false, sector:'Zorg' }
  ];

  var contacts = [
    { id:'c1', vn:'Koen', an:'Bolckmans', email:'koen@bolckmans.be', gsm:'0475 22 11 90', bedrijfId:'bolckmans', notif:'Beide', kanalen:['WhatsApp','E-mail'] },
    { id:'c2', vn:'Sofie', an:'Janssens', email:'sofie.janssens@bolckmans.be', gsm:'0478 55 21 33', bedrijfId:'bolckmans', notif:'E-mail', kanalen:['E-mail'] },
    { id:'c3', vn:'Tom', an:'Peeters', email:'tom.peeters@bolckmans.be', gsm:'0496 11 87 02', bedrijfId:'bolckmans', notif:'WhatsApp', kanalen:['WhatsApp','Push'] },
    { id:'c4', vn:'Floris', an:'De Cock', email:'floris@florvastgoed.be', gsm:'0471 90 22 18', bedrijfId:'flor', notif:'E-mail', kanalen:['E-mail'] },
    { id:'c5', vn:'Anke', an:'Mertens', email:'anke@florvastgoed.be', gsm:'0488 21 55 70', bedrijfId:'flor', notif:'Beide', kanalen:['WhatsApp','E-mail'] },
    { id:'c6', vn:'Melanie', an:'Raes', email:'melanie@dermaraes.be', gsm:'0470 33 12 88', bedrijfId:'raes', notif:'WhatsApp', kanalen:['WhatsApp'] },
    { id:'c7', vn:'Bart', an:'Vermeulen', email:'bart.vermeulen@partspoint.be', gsm:'0495 77 21 09', bedrijfId:'partspoint', notif:'E-mail', kanalen:['E-mail','Push'] },
    { id:'c8', vn:'Ellen', an:'Goossens', email:'ellen.goossens@partspoint.be', gsm:'0479 11 90 44', bedrijfId:'partspoint', notif:'Geen', kanalen:[] },
    { id:'c9', vn:'Wim', an:'Aerts', email:'wim@abwbestratingen.be', gsm:'0486 22 70 11', bedrijfId:'abw', notif:'Beide', kanalen:['WhatsApp','E-mail'] },
    { id:'c10', vn:'Geert', an:'Vorsselmans', email:'geert@vorsselmans.be', gsm:'0475 90 12 33', bedrijfId:'vorsselmans', notif:'E-mail', kanalen:['E-mail'] },
    { id:'c11', vn:'Lien', an:'Smets', email:'lien@vorsselmans.be', gsm:'0498 33 21 76', bedrijfId:'vorsselmans', notif:'WhatsApp', kanalen:['WhatsApp','Push'] },
    { id:'c12', vn:'Dirk', an:'Maes', email:'dirk.maes@gtfoam.com', gsm:'0477 21 88 90', bedrijfId:'gtfoam', notif:'E-mail', kanalen:['E-mail'] },
    { id:'c13', vn:'Nele', an:'Claes', email:'nele@orison.be', gsm:'0496 70 11 22', bedrijfId:'orison', notif:'Beide', kanalen:['WhatsApp','E-mail'] },
    { id:'c14', vn:'Jeroen', an:'Willems', email:'jeroen@maxpro.be', gsm:'0471 55 90 21', bedrijfId:'maxpro', notif:'Geen', kanalen:[] },
    { id:'c15', vn:'Patrick', an:'Boon', email:'patrick@ipcleaning.be', gsm:'0488 12 33 70', bedrijfId:'ipcleaning', notif:'E-mail', kanalen:['E-mail'] },
    { id:'c16', vn:'Karel', an:'Rodenburgh', email:'karel@rodenburgh.be', gsm:'0475 33 21 09', bedrijfId:'rodenburgh', notif:'WhatsApp', kanalen:['WhatsApp'] },
    { id:'c17', vn:'Maarten', an:'Van Genechten', email:'maarten@mvg-coaching.be', gsm:'0479 90 12 88', bedrijfId:'genechten', notif:'WhatsApp', kanalen:['WhatsApp'] },
    { id:'c18', vn:'Greet', an:'Adams', email:'greet@gyma.be', gsm:'0496 21 70 33', bedrijfId:'gyma', notif:'Beide', kanalen:['WhatsApp','E-mail'] },
    { id:'c19', vn:'Hilde', an:'Verbeeck', email:'hilde@farmamatch.be', gsm:'0470 88 21 11', bedrijfId:'farmamatch', notif:'E-mail', kanalen:['E-mail'] },
    { id:'c20', vn:'Stijn', an:'Coenen', email:'stijn@eyematch.be', gsm:'0488 90 33 21', bedrijfId:'eyematch', notif:'Beide', kanalen:['WhatsApp','E-mail'] }
  ];

  var offertes = [
    { id:'of1', titel:'Bolckmans NV - Website + SEO + Automation', status:'completed', bedrijfId:'bolckmans', contactId:'c1', meetingId:'mt2', briefingId:'br1', panda:'PD-99201', link:'app.pandadoc.com/d/99201', code:'S27-2026-014', verval:'30 jun 2026', doorzet:'Done', budget:24500, deel:{Strategie:2500,Branding:0,'Video- en fotografie':3000,Webdesign:11000,'Social media':0,Adverteren:0,Automations:6000,Opleidingen:2000}, extra:'Goedgekeurd na tweede meeting. Projecttaken aangemaakt in ClickUp.' },
    { id:'of2', titel:'Flor Vastgoed - 27A automation retainer', status:'completed', bedrijfId:'flor', contactId:'c4', meetingId:'mt3', briefingId:'br2', panda:'PD-77410', link:'app.pandadoc.com/d/77410', code:'27A-2026-008', verval:'01 jul 2026', doorzet:'Done', budget:1450, deel:{Strategie:0,Branding:0,'Video- en fotografie':0,Webdesign:0,'Social media':0,Adverteren:0,Automations:1450,Opleidingen:0}, extra:'Maandelijkse retainer. Recurring revenue.' },
    { id:'of3', titel:'Dr. Melanie Raes - Praktijkbranding', status:'sent', bedrijfId:'raes', contactId:'c6', meetingId:'mt4', briefingId:null, panda:'PD-33205', link:'app.pandadoc.com/d/33205', code:'S27-2026-021', verval:'05 jul 2026', doorzet:'Naar PM', budget:6800, deel:{Strategie:1200,Branding:4600,'Video- en fotografie':1000,Webdesign:0,'Social media':0,Adverteren:0,Automations:0,Opleidingen:0}, extra:'' },
    { id:'of4', titel:'PartsPoint - Videocampagne Q3', status:'viewed', bedrijfId:'partspoint', contactId:'c7', meetingId:'mt5', briefingId:'br3', panda:'PD-55124', link:'app.pandadoc.com/d/55124', code:'S27-2026-019', verval:'02 jul 2026', doorzet:'Naar PM', budget:18900, deel:{Strategie:1900,Branding:0,'Video- en fotografie':8000,Webdesign:0,'Social media':3000,Adverteren:6000,Automations:0,Opleidingen:0}, extra:'Bekeken op 21 jun, nog geen reactie.' },
    { id:'of5', titel:'ABW Bestratingen - SEO-pakket', status:'completed', bedrijfId:'abw', contactId:'c9', meetingId:null, briefingId:null, panda:'PD-99120', link:'app.pandadoc.com/d/99120', code:'S27-2026-006', verval:'15 jun 2026', doorzet:'Done', budget:4200, deel:{Strategie:700,Branding:0,'Video- en fotografie':1500,Webdesign:0,'Social media':0,Adverteren:0,Automations:0,Opleidingen:2000}, extra:'' },
    { id:'of6', titel:'Vorsselmans Solar - Branding refresh', status:'draft', bedrijfId:'vorsselmans', contactId:'c10', meetingId:'mt6', briefingId:'br4', panda:'PD-88201', link:'app.pandadoc.com/d/88201', code:'S27-2026-024', verval:'10 jul 2026', doorzet:'Naar PM', budget:9300, deel:{Strategie:1300,Branding:6000,'Video- en fotografie':2000,Webdesign:0,'Social media':0,Adverteren:0,Automations:0,Opleidingen:0}, extra:'Nog niet verzonden, wacht op extra info.' },
    { id:'of7', titel:'GT Foam - Social opstart', status:'sent', bedrijfId:'gtfoam', contactId:'c12', meetingId:'mt7', briefingId:null, panda:'PD-22310', link:'app.pandadoc.com/d/22310', code:'S27-2026-022', verval:'04 jul 2026', doorzet:'Naar PM', budget:5400, deel:{Strategie:600,Branding:0,'Video- en fotografie':1800,Webdesign:0,'Social media':3000,Adverteren:0,Automations:0,Opleidingen:0}, extra:'' },
    { id:'of8', titel:'Orison - Adverteren Meta', status:'completed', bedrijfId:'orison', contactId:'c13', meetingId:'mt8', briefingId:'br5', panda:'PD-66102', link:'app.pandadoc.com/d/66102', code:'S27-2026-011', verval:'20 jun 2026', doorzet:'Done', budget:7200, deel:{Strategie:600,Branding:0,'Video- en fotografie':1200,Webdesign:0,'Social media':1400,Adverteren:4000,Automations:0,Opleidingen:0}, extra:'' },
    { id:'of9', titel:'Max Pro - Website', status:'declined', bedrijfId:'maxpro', contactId:'c14', meetingId:null, briefingId:null, panda:'PD-44120', link:'app.pandadoc.com/d/44120', code:'S27-2026-003', verval:'01 mei 2026', doorzet:'Naar PM', budget:8800, deel:{Strategie:800,Branding:0,'Video- en fotografie':2000,Webdesign:6000,'Social media':0,Adverteren:0,Automations:0,Opleidingen:0}, extra:'Afgewezen: budget niet rond.' },
    { id:'of10', titel:'IP Cleaning - SEO', status:'expired', bedrijfId:'ipcleaning', contactId:'c15', meetingId:null, briefingId:null, panda:'PD-11209', link:'app.pandadoc.com/d/11209', code:'S27-2026-001', verval:'20 mrt 2026', doorzet:'Naar PM', budget:3600, deel:{Strategie:600,Branding:0,'Video- en fotografie':1000,Webdesign:0,'Social media':0,Adverteren:0,Automations:0,Opleidingen:2000}, extra:'Vervallen door tijd.' },
    { id:'of11', titel:'Farmamatch - Strategie zorgmarketing', status:'draft', bedrijfId:'farmamatch', contactId:'c19', meetingId:'mt9', briefingId:null, panda:'PD-11901', link:'app.pandadoc.com/d/11901', code:'ZVD-2026-005', verval:'12 jul 2026', doorzet:'Naar PM', budget:5900, deel:{Strategie:3900,Branding:0,'Video- en fotografie':2000,Webdesign:0,'Social media':0,Adverteren:0,Automations:0,Opleidingen:0}, extra:'' },
    { id:'of12', titel:'Eyematch - Webdesign + hosting', status:'viewed', bedrijfId:'eyematch', contactId:'c20', meetingId:'mt10', briefingId:'br6', panda:'PD-44209', link:'app.pandadoc.com/d/44209', code:'ZVD-2026-009', verval:'08 jul 2026', doorzet:'Naar PM', budget:12400, deel:{Strategie:1400,Branding:0,'Video- en fotografie':0,Webdesign:9000,'Social media':0,Adverteren:0,Automations:2000,Opleidingen:0}, extra:'' }
  ];

  var senderByOff = { of1:'Arne', of2:'Ilke', of3:'Arne', of4:'Ilke', of5:'Arne', of6:'Johanna', of7:'Arne', of8:'Johanna', of9:'Arne', of10:'Arne', of11:'Arne', of12:'Ilke' };

  // ===== Canonieke PandaDoc-offertestatus (gedeeld door CRM + Finance + bruidsparen) =====
  // Volgorde = de PandaDoc-flow waarlangs een offerte loopt; declined/expired zijn eindpunten buiten de flow.
  var offerteStatusMeta = {
    draft:     { label:'Concept',   bg:'#EFEADD', fg:'#5E5A4F', dot:'#A8A293', flow:0 },
    sent:      { label:'Verzonden', bg:'#E2E9FC', fg:'#0F2EA3', dot:'#2458EA', flow:1 },
    viewed:    { label:'Bekeken',   bg:'#E0F1FD', fg:'#0F2EA3', dot:'#28AFF9', flow:2 },
    completed: { label:'Getekend',  bg:'#F4FBDB', fg:'#4A6B0E', dot:'#7BA905', flow:3 },
    declined:  { label:'Geweigerd', bg:'#F7E0DB', fg:'#6E2218', dot:'#B83A2A', flow:-1 },
    expired:   { label:'Vervallen', bg:'#EAE6D8', fg:'#8E8979', dot:'#8E8979', flow:-1 }
  };
  // De zichtbare voortgangsstappen (de "track" die gevolgd kan worden)
  var offerteStatusFlow = ['draft','sent','viewed','completed'];
  function offerteStatus(s){ return offerteStatusMeta[s] || offerteStatusMeta.draft; }

  window.S27_DATA = { offertes:offertes, companies:companies, contacts:contacts, senderByOff:senderByOff,
    offerteStatusMeta:offerteStatusMeta, offerteStatusFlow:offerteStatusFlow, offerteStatus:offerteStatus };
})();
